services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: 767397934648.dkr.ecr.ap-northeast-1.amazonaws.com/newtralize-web:latest
    ports:
      - "8080:80"
    env_file:
      - ./.env.prod
    environment:
      APACHE_SERVER_NAME: dev.newtralize.com
