services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: 767397934648.dkr.ecr.ap-northeast-1.amazonaws.com/newtralize-web:latest
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - ./.env.prod
    volumes:
      - .:/var/www/newtralize
