services:
  web:
    build:
      context: ./
      dockerfile: Dockerfile.prod
    image: 767397934648.dkr.ecr.ap-northeast-1.amazonaws.com/newtralize-web:latest
    ports:
      - "8080:80"
    env_file:
      - ./.env.prod
    environment:
      APACHE_SERVER_NAME: dev.newtralize.com
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
