# This file is used to override the docker-compose.prod.yml file for local testing
services:
  web:
    platform: linux/arm64
    volumes:
      - ./.env:/var/www/newtralize/.env
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    env_file:
      - ./.env
    environment:
      DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
