services:
  web:
    environment:
      APACHE_SERVER_NAME: localhost
      DB_HOST: mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    env_file:
      - ./.env.prod
    environment:
      DB_HOST: mysql
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
